#!/bin/bash
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

AUTOTEST=/mnt/host/source/src/third_party/autotest/files
SCR=$AUTOTEST/site_utils/bootperf-bin/$(basename $0)

if [ ! -f $SCR ]; then
  echo "You appear to have a minilayout checkout, without the autotest"
  echo "repository in your source tree. Aborting."
  exit 1
fi

exec $SCR "$@"
