#!/bin/bash

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# TODO(bsimonnet): Remove after July 2015.
echo "This script is deprecated. Please use cros_run_unit_tests from "
echo "chromite/bin."

exit 1
